  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: orderprocessing-app-deployment
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: order-app
    template:
      metadata:
        labels:
          app: order-app
      spec:
        containers:
        - name: order-app
          image: mtaori/orderprocessing:latest
          ports:
          - containerPort: 5040
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PORT
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: NODE_ENV
